=== phrynchanka/Test/resource/devices.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.training.by/devices"
        xmlns:tns="http://www.epam.training.by/devices"
        elementFormDefault="unqualified"
        attributeFormDefault="unqualified"
        >
    <element name="devices">
        <complexType>
            <sequence>
                <element name="computer"
                         type="tns:Computer"
                         minOccurs="1"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Computer">
        <sequence>
            <element name="name"
                     type="tns:NamePattern"/>
            <element name="origin"
                     type="tns:NamePattern"/>
            <element name="price"
                     type="nonNegativeInteger"/>
            <element name="type"
                     type="tns:Type"/>
            <element name="critical"
                     type="boolean"/>
        </sequence>
        <attribute name="id"
                   type="tns:ComputerID"
                   use="required"/>
    </complexType>
    <complexType name="Type">
        <sequence>
            <element name="peripheral"
                     type="boolean"/>
            <element name="power"
                     type="nonNegativeInteger"/>
            <element name="hardware"
                     type="tns:Hardware"/>
        </sequence>
    </complexType>
    <complexType name="Hardware">
        <sequence>
            <element name="monitor"
                     type="boolean"/>
            <element name="harddisk"
                     type="boolean"/>
            <element name="motherboard"
                     type="boolean"/>
            <element name="cooling"
                     type="boolean"/>
            <element name="mouse"
                     type="boolean"/>
            <element name="keyboard"
                     type="boolean"/>
            <element name="processor"
                     type="boolean"/>
            <element name="videocard"
                     type="boolean"/>
            <element name="socket"
                     type="tns:Socket"/>
        </sequence>
    </complexType>
    <simpleType name="Socket">
        <restriction base="string">
            <enumeration value="USB"/>
            <enumeration value="COM"/>
            <enumeration value="LPT"/>
        </restriction>
    </simpleType>
    <simpleType name="NamePattern">
        <restriction base="string">
            <pattern value="([A-Z]+[a-z]* *[A-Z]*[a-z]*)"/>
            <maxLength value="20"/>
        </restriction>
    </simpleType>
    <simpleType name="ComputerID">
        <restriction base="ID">
            <pattern value="([a-z0-9]+)"/>
        </restriction>
    </simpleType>
</schema>

=== phrynchanka/Test/resource/devices.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:devices xmlns:tns="http://www.epam.training.by/devices"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.epam.training.by/devices devices.xsd">
    <computer id="x0000000001">
        <name>Lenovo</name>
        <origin>China</origin>
        <price>200</price>
        <type>
            <peripheral>false</peripheral>
            <power>20</power>
            <hardware>
                <monitor>false</monitor>
                <harddisk>false</harddisk>
                <motherboard>false</motherboard>
                <cooling>true</cooling>
                <mouse>true</mouse>
                <keyboard>false</keyboard>
                <processor>true</processor>
                <videocard>false</videocard>
                <socket>COM</socket>
            </hardware>
        </type>
        <critical>false</critical>
    </computer>
    <computer id="x0000000002">
        <name>Lenovo</name>
        <origin>China</origin>
        <price>300</price>
        <type>
            <peripheral>true</peripheral>
            <power>20</power>
            <hardware>
                <monitor>true</monitor>
                <harddisk>true</harddisk>
                <motherboard>true</motherboard>
                <cooling>false</cooling>
                <mouse>false</mouse>
                <keyboard>false</keyboard>
                <processor>false</processor>
                <videocard>true</videocard>
                <socket>USB</socket>
            </hardware>
        </type>
        <critical>false</critical>
    </computer>
    <computer id="x0000000003">
        <name>Acer</name>
        <origin>Taiwan</origin>
        <price>200</price>
        <type>
            <peripheral>false</peripheral>
            <power>70</power>
            <hardware>
                <monitor>true</monitor>
                <harddisk>true</harddisk>
                <motherboard>false</motherboard>
                <cooling>true</cooling>
                <mouse>true</mouse>
                <keyboard>true</keyboard>
                <processor>false</processor>
                <videocard>false</videocard>
                <socket>LPT</socket>
            </hardware>
        </type>
        <critical>false</critical>
    </computer>
    <computer id="x0000000004">
        <name>Apple</name>
        <origin>United States</origin>
        <price>850</price>
        <type>
            <peripheral>false</peripheral>
            <power>100</power>
            <hardware>
                <monitor>true</monitor>
                <harddisk>false</harddisk>
                <motherboard>true</motherboard>
                <cooling>false</cooling>
                <mouse>true</mouse>
                <keyboard>true</keyboard>
                <processor>false</processor>
                <videocard>false</videocard>
                <socket>COM</socket>
            </hardware>
        </type>
        <critical>false</critical>
    </computer>
    <computer id="x0000000005">
        <name>Asus</name>
        <origin>Taiwan</origin>
        <price>400</price>
        <type>
            <peripheral>false</peripheral>
            <power>90</power>
            <hardware>
                <monitor>false</monitor>
                <harddisk>true</harddisk>
                <motherboard>true</motherboard>
                <cooling>false</cooling>
                <mouse>false</mouse>
                <keyboard>true</keyboard>
                <processor>true</processor>
                <videocard>true</videocard>
                <socket>LPT</socket>
            </hardware>
        </type>
        <critical>false</critical>
    </computer>
    <computer id="x0000000006">
        <name>Dell</name>
        <origin>United States</origin>
        <price>900</price>
        <type>
            <peripheral>false</peripheral>
            <power>25</power>
            <hardware>
                <monitor>false</monitor>
                <harddisk>false</harddisk>
                <motherboard>false</motherboard>
                <cooling>false</cooling>
                <mouse>true</mouse>
                <keyboard>false</keyboard>
                <processor>true</processor>
                <videocard>true</videocard>
                <socket>COM</socket>
            </hardware>
        </type>
        <critical>true</critical>
    </computer>
    <computer id="x0000000007">
        <name>HP</name>
        <origin>United States</origin>
        <price>800</price>
        <type>
            <peripheral>false</peripheral>
            <power>40</power>
            <hardware>
                <monitor>true</monitor>
                <harddisk>false</harddisk>
                <motherboard>true</motherboard>
                <cooling>true</cooling>
                <mouse>true</mouse>
                <keyboard>false</keyboard>
                <processor>false</processor>
                <videocard>false</videocard>
                <socket>USB</socket>
            </hardware>
        </type>
        <critical>true</critical>
    </computer>
    <computer id="x0000000008">
        <name>Lenovo</name>
        <origin>China</origin>
        <price>250</price>
        <type>
            <peripheral>false</peripheral>
            <power>70</power>
            <hardware>
                <monitor>false</monitor>
                <harddisk>false</harddisk>
                <motherboard>true</motherboard>
                <cooling>true</cooling>
                <mouse>false</mouse>
                <keyboard>false</keyboard>
                <processor>false</processor>
                <videocard>false</videocard>
                <socket>LPT</socket>
            </hardware>
        </type>
        <critical>true</critical>
    </computer>
    <computer id="x0000000009">
        <name>Toshiba</name>
        <origin>Japan</origin>
        <price>800</price>
        <type>
            <peripheral>false</peripheral>
            <power>10</power>
            <hardware>
                <monitor>false</monitor>
                <harddisk>false</harddisk>
                <motherboard>false</motherboard>
                <cooling>true</cooling>
                <mouse>true</mouse>
                <keyboard>true</keyboard>
                <processor>false</processor>
                <videocard>false</videocard>
                <socket>USB</socket>
            </hardware>
        </type>
        <critical>true</critical>
    </computer>
    <computer id="x0000000010">
        <name>Samsung</name>
        <origin>South Korea</origin>
        <price>950</price>
        <type>
            <peripheral>false</peripheral>
            <power>50</power>
            <hardware>
                <monitor>false</monitor>
                <harddisk>false</harddisk>
                <motherboard>true</motherboard>
                <cooling>true</cooling>
                <mouse>true</mouse>
                <keyboard>true</keyboard>
                <processor>false</processor>
                <videocard>false</videocard>
                <socket>USB</socket>
            </hardware>
        </type>
        <critical>false</critical>
    </computer>
    <computer id="x0000000011">
        <name>Lenovo</name>
        <origin>China</origin>
        <price>750</price>
        <type>
            <peripheral>false</peripheral>
            <power>60</power>
            <hardware>
                <monitor>true</monitor>
                <harddisk>false</harddisk>
                <motherboard>true</motherboard>
                <cooling>true</cooling>
                <mouse>true</mouse>
                <keyboard>false</keyboard>
                <processor>false</processor>
                <videocard>true</videocard>
                <socket>LPT</socket>
            </hardware>
        </type>
        <critical>false</critical>
    </computer>
    <computer id="x0000000012">
        <name>Lenovo</name>
        <origin>China</origin>
        <price>900</price>
        <type>
            <peripheral>false</peripheral>
            <power>10</power>
            <hardware>
                <monitor>false</monitor>
                <harddisk>false</harddisk>
                <motherboard>false</motherboard>
                <cooling>true</cooling>
                <mouse>false</mouse>
                <keyboard>false</keyboard>
                <processor>false</processor>
                <videocard>true</videocard>
                <socket>LPT</socket>
            </hardware>
        </type>
        <critical>true</critical>
    </computer>
    <computer id="x0000000013">
        <name>Acer</name>
        <origin>Taiwan</origin>
        <price>450</price>
        <type>
            <peripheral>false</peripheral>
            <power>45</power>
            <hardware>
                <monitor>true</monitor>
                <harddisk>false</harddisk>
                <motherboard>true</motherboard>
                <cooling>false</cooling>
                <mouse>false</mouse>
                <keyboard>false</keyboard>
                <processor>true</processor>
                <videocard>true</videocard>
                <socket>USB</socket>
            </hardware>
        </type>
        <critical>false</critical>
    </computer>
    <computer id="x0000000014">
        <name>Apple</name>
        <origin>United States</origin>
        <price>800</price>
        <type>
            <peripheral>false</peripheral>
            <power>10</power>
            <hardware>
                <monitor>false</monitor>
                <harddisk>false</harddisk>
                <motherboard>true</motherboard>
                <cooling>true</cooling>
                <mouse>false</mouse>
                <keyboard>false</keyboard>
                <processor>true</processor>
                <videocard>false</videocard>
                <socket>LPT</socket>
            </hardware>
